version: '3.4'
volumes:
  bundles:
  pg_data:
  node_modules:
services:
  app:
    build: .
    command: rails server -p 3000 -b 0.0.0.0
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@db/dev
    links:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundles:/usr/local/bundle:delegated
      - node_modules:/app/node_modules:delegated

  db:
    container_name: postgres-9.6
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data

  spring:
    build: .
    command: spring server
    environment:
      DATABASE_URL: postgres://postgres@db/dev
    # This ensures that the pid namespace is shared between the host
    # and the container. It's not necessary to be able to run spring
    # commands, but it is necessary for "spring status" and "spring stop"
    # to work properly.
    pid: host
    volumes:
      - .:/app
      - bundles:/usr/local/bundle:delegated
